---
- name: add Apt signing key from hashicorp
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: set lsb_release
  ansible.builtin.command: lsb_release -cs
  register: lsbrelease

- name: Add hashicorp repo
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ lsbrelease }}  main"
    state: present

- name: Install terraform
  apt:
    name: terraform
    state: latest
    update_cache: yes

...
