---
- name: install needed packages for nfs
  apt:
    name: nfs-common
    state: latest

- name: creating needed dirs
  file:
    path: "/home/{{ ansible_user_id }}/ds/{{ item }}"
    state: directory
    owner: "{{ roleVarUser }}"
    mode: 0700
  with_items:
    - music
    - video
    - photo 
    - home

- name: mounting dsFileSystems
  mount:
    path: "/home/{{ ansible_user_id }}/ds/{{ item }}"
    src: "{{ roleVarSynologyIp }}:/volume1/{{ item }}/"
    fstype: nfs4
    opts: rw,auto,users,bg
    state: mounted
  with_items:
    - music
    - video
    - photo
    - home
...
